### ISSUE TITLE
accessToken seems to be needed

### ISSUE THREAD

**Issue by halsk** [optgeo/s#19]
最初は表示されるのだが、ずっと待っていると以下のエラーがコンソールに表示され、地図が出なくなります。

![image](https://user-images.githubusercontent.com/16509/116770942-6e6c6500-aa82-11eb-84d4-1428fe0bd024.png)

#12 で削除された影響かと。

**Comment by hfu** [comment]
ありがとうございました！おかげさまで復帰させることができましたので、クローズします。
