### ISSUE TITLE
js.sabae.cc へのアクセスが遮断される残念な環境がある

### ISSUE THREAD

**Issue by hfu** [optgeo/s#24]
残念ながら、行政のネットワーク環境で https://js.sabae.cc/YAML.js などの js.sabae.cc ドメインへのアクセスが遮断される例が見つかりました。

取り急ぎ共有まで。
@taisukef

**Comment by taisukef** [comment]
おや、そんなことが！
githubでも同一のものがあるので、そちらに切り替えておくのが無難かも・・・
https://code4sabae.github.io/js/YAML.js

**Comment by hfu** [comment]
ネットワーク側の問題であるにも関わらず、柔軟かつ積極的にご対応くださりありがとうございます！
