### ISSUE TITLE
データで緯度経度を指定する方法

### ISSUE THREAD

**Issue by taisukef** [optgeo/s#5]
hashがなく、lat/lng/zoomというパラメーターがあればそれを使うのはどうでしょう？
ついでに、geo3x3があったら使うようにしてみたコードで試しています
https://github.com/taisukef/s/blob/geo3x3/docs/module.js#L49-L79

**Comment by hfu** [comment]
本件拡張に異存ないです！ありがとうございます。

**Comment by halsk** [comment]
私もそれやりたいと思っていました。

**Comment by taisukef** [comment]
ひとまず、プルリク送りますー
https://github.com/optgeo/s/pull/6

**Comment by hfu** [comment]
プリリクありがとうございます！マージしました！
