### ISSUE TITLE
Specify data location by URL parameters

### ISSUE THREAD

**Issue by halsk** [optgeo/s#7]
If users can pass the document URL of story data, users don't need to create HTML each time.

**Comment by hfu** [comment]
いいですね！ maputnik にあるみたいな感じでしょうか。

つまり、`https://optgeo.github.io/s/story=https://example.com/somewhere/story.yml` みたいな URL で渡せるようにすると、オーサーは単に YAML ファイルだけウェブに上げれば良くなるということかなと理解しています。

**Comment by halsk** [comment]
Yes, exactly. Let me take this issue.

**Comment by halsk** [comment]
あー、僕が今Pushしたコードは、config.chapters 部分のみをパラメータで指定できるようにしています。
それは、現行のコードがこうなっているからです。

```
        const yml = await (await fetch(url)).text();
        config.chapters = YAML.parse(yml);
```
